version: '3.3'

services:
  # main:
  #     container_name: nodeJS
  #     image: node:14.18.0
  #     ports:
  #       - 3000:3000
  #       - 9229:9229
  #     working_dir: /src/app/
  #     volumes:
  #       - './:/src/app'
  #       - './node_modules:/app/node_modules'
  #     command: npm run dev
  #     depends_on:
  #       - mysql

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_wallet
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=team2
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    # container_name: mysql-client
    image: phpmyadmin/phpmyadmin
    # restart: always
    # depends_on:
      # - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=team2
      - PMA_HOST=mysql
    ports:
      - 8080:80
